<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# Lists, Arrays & Dictionaries

## Let’s compare

__Python lists__ 

In [1]:
py_days = ['Monday', 'Tuesday', 'Wednesday']
py_days_m=['Davaa', 'Myagmar', 'Lkhagva']

__Numpy Arrays__

In [3]:
import numpy as np 
np_days = np.array(['Monday', 'Tuesday', 'Wednesday'])
np_days_m = np.array(['Davaa', 'Myagmar', 'Lkhagva'])

__Dictionary__ 

In [13]:
days_info = {
    'Monday': 'Davaa',
    'Tuesday': 'Myagmar',
    'Wednesday': 'Lkhagva'
}

- Dictionaries use a key and an associated value separated by a: 
- Order matters for lists and arrays. 

## Accessing data from a list (or array)

To access data from lists and arrays, indexing is needed. Python starts counting at 0. 

In [10]:
days = ['Monday', 'Tuesday', 'Wednesday']
days_m=['Davaa', 'Myagmar', 'Lkhagva']
days_m[1]

'Myagmar'

In [12]:
days[-1] #Reverse indexing helps us when we don't know the total number of items. 

'Wednesday'

## Accessing data from a dictionary

In [14]:
days_info = {
    'Monday': 'Davaa',
    'Tuesday': 'Myagmar',
    'Wednesday': 'Lkhagva'
}
days_info['Wednesday']

'Lkhagva'

In [17]:
days_info. keys()

dict_keys(['Monday', 'Tuesday', 'Wednesday'])

In [18]:
days_info. values()

dict_values(['Davaa', 'Myagmar', 'Lkhagva'])

## Higher dimensional lists

To make a single structure using lists: 

In [21]:
days_info = [['Monday', 'Davaa'], 
             ['Tuesday', 'Myagmar'], 
             ['Wednesday', 'Lkhagva']]

# Lists vs. Arrays

## Size

The len() function tells you how many elements are in a list or an array. 

In [27]:
import numpy as np 
days_info = [['Monday', 'Davaa'], ['Tuesday', 'Myagmar'], ['Wednesday', 'Lkhagva']]
array_days_info = np. array(days_info) #to convert a list into an array 

In [28]:
len(days_info)

3

In [29]:
len(array_days_info)

3

In [30]:
array_days_info.shape #shape is not a function but a property of the numpy array. 

(3, 2)

## Arrays are fussy about type

In [ ]:
Arrays can hold only one type of data, while lists can hold multiple. 

In [32]:
list = [1, 2 ,'hi']
import numpy as np 
array = np. array (list)

In [33]:
list 

[1, 2, 'hi']

In [34]:
array 

array(['1', '2', 'hi'], dtype='<U11')

The above can be fixed with a function astypes()

## Adding another list 

In [35]:
list1 = [1, 2, 3, 4]
list2 = [11, 12, 13, 14]
import numpy as np 
array1 = np.array (list1)
array2 = np.array (list2)

In [36]:
list1 + list2 

[1, 2, 3, 4, 11, 12, 13, 14]

In [37]:
array1 + array2 

array([12, 14, 16, 18])

Operations on arrays are element-wise. 

## Adding a number 

In [39]:
list = [1, 2, 3, 4]
array = np.array (list)

In [40]:
array+ 10 

array([11, 12, 13, 14])

In [ ]:
list+10 # This will result in an error. 

## Multiplying by a Number

In [ ]:
list = [1, 2, 3, 4]
array = np.array (list)

In [42]:
list*3 

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [43]:
array*3 

array([ 3,  6,  9, 12])

## Squaring

In [45]:
list = [1, 2, 3, 4]
array = np.array (list)

Since squaring is just multiplying twice, you can guess that operations on an array will work but not on lists. 

## Asking questions

In [46]:
list = [1, 2, 3, 4]
array = np.array (list)

In [47]:
list == 3 

False

In [48]:
array == 3

array([False, False,  True, False])

In [49]:
list == 4 

False

In [50]:
array>2 

array([False, False,  True,  True])

Operations on arrays will be made on each element. Thus ==3 checks which element is equal to 3, >2 checks which element is greater than 2. 

list == n will always be false, because you are comparing a single value to a list 

## Mathematics 

In [52]:
list = [1, 2, 3, 4]
array = np.array (list)

In [55]:
sum(list)     # sum() is a base Python function

10

In [56]:
max(list)     # max() is a base Python function

4

In [58]:
min(list)     # min() is a base Python function

1

In [59]:
array.sum()

10

In [60]:
array.max()

4

In [61]:
array.min()

1

In [62]:
array.mean()

2.5

In [63]:
array.std()

1.118033988749895